import os


def run_claude_stage(user_task, session_dir, chatgpt_result):
    # Placeholder function
    print("Running Claude stage...")
    result = "This is the final study generated by Claude."
    usage = {
        "used_k": 0.0,
        "max_k": 80.0,
    }

    # Create placeholder file
    final_dir = os.path.join(session_dir, "03_final")
    with open(os.path.join(final_dir, "estudo_final.md"), "w", encoding="utf-8") as f:
        f.write(result)

    return result, usage
