import os
import json
import yaml
from dotenv import load_dotenv
import anthropic

# Load environment variables from .env file
load_dotenv()

def load_prompt(filepath):
    """Loads a prompt from a file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        print(f"Warning: Prompt file not found at {filepath}")
        return ""

def read_chatgpt_outputs(session_dir):
    """Reads all the files generated by the ChatGPT stage."""
    raw_dir = os.path.join(session_dir, "01_raw")

    summary = load_prompt(os.path.join(raw_dir, "summary.md"))

    sources = []
    try:
        with open(os.path.join(raw_dir, "sources.json"), "r", encoding="utf-8") as f:
            sources = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        print("Warning: sources.json not found or is invalid.")

    notes_dir = os.path.join(raw_dir, "notes")
    notes = {}
    if os.path.isdir(notes_dir):
        for filename in os.listdir(notes_dir):
            topic = filename.replace("_", " ").replace(".md", "")
            notes[topic] = load_prompt(os.path.join(notes_dir, filename))

    return summary, sources, notes

def run_claude_stage(user_task, session_dir, chatgpt_result):
    """
    Runs the Claude stage to analyze the collected data and generate the final study.
    """
    print("Running Claude stage...")

    # 1. Load configuration
    with open("config/claude_config.yaml", "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    # 2. Load the content generated by the ChatGPT stage
    summary, sources, notes = read_chatgpt_outputs(session_dir)

    # 3. Load Claude's prompts
    system_prompt = load_prompt("prompts/claude_system.md")
    format_prompt = load_prompt("prompts/claude_format.md")

    # 4. Construct the full prompt for the API
    user_prompt_content = (
        f"Here is the research on the topic '{user_task}'. Please generate the final study.\\n\\n"
        f"--- SUMMARY ---\\n{summary}\\n\\n"
        f"--- SOURCES ---\\n{json.dumps(sources, indent=2)}\\n\\n"
        f"--- DETAILED NOTES ---\\n"
    )
    for topic, content in notes.items():
        user_prompt_content += f"Topic: {topic}\\n{content}\\n\\n"

    # 5. Initialize the client and call the Anthropic API
    client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

    result = ""
    usage = {}

    try:
        response = client.messages.create(
            model=config["model"],
            max_tokens=config.get("max_output_tokens", 4096),
            system=f"{system_prompt}\\n\\n{format_prompt}",
            messages=[
                {"role": "user", "content": user_prompt_content}
            ]
        )

        result = response.content[0].text

        usage = {
            "model": config["model"],
            "used_k": (response.usage.input_tokens + response.usage.output_tokens) / 1000,
            "max_k": config["max_context_tokens"] / 1000,
            "used_tokens": response.usage.input_tokens + response.usage.output_tokens,
            "max_context_tokens": config["max_context_tokens"],
        }

    except Exception as e:
        print(f"An error occurred while calling the Anthropic API: {e}")
        result = "Error: Could not generate the final study from Anthropic API."
        usage = {
            "model": config.get("model", "unknown"),
            "used_k": 0,
            "max_k": config.get("max_context_tokens", 0) / 1000,
            "used_tokens": 0,
            "max_context_tokens": config.get("max_context_tokens", 0),
        }

    # 6. Save the final study
    final_dir = os.path.join(session_dir, "03_final")
    os.makedirs(final_dir, exist_ok=True)
    with open(os.path.join(final_dir, "estudo_final.md"), "w", encoding="utf-8") as f:
        f.write(result)

    return result, usage
